# Generated by Django 4.2.7 on 2025-08-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="链接标题")),
                ("url", models.URLField(verbose_name="链接地址")),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "网站"),
                            ("tool", "工具"),
                            ("resource", "资源"),
                            ("documentation", "文档"),
                            ("other", "其他"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="链接类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "外部链接",
                "verbose_name_plural": "外部链接",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
