# Generated by Django 5.2.4 on 2025-08-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标签别名')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('color', models.CharField(default='#67C23A', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'categories_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活')], default='active', max_length=10, verbose_name='状态')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#409EFF', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories_category',
                'ordering': ['order', 'name'],
            },
        ),
    ]
