"""
Django settings for alpha project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps to Python path
import sys
import os
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-alpha-tech-share-platform-2024')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

# CSRF trusted origins (comma-separated), e.g.
# DJANGO_CSRF_TRUSTED_ORIGINS="http://8.129.16.190:8003,http://8.129.16.190,https://8.129.16.190"
_csrf_origins_env = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins_env.split(',') if o.strip()] if _csrf_origins_env else []

# Auto-derive CSRF_TRUSTED_ORIGINS from ALLOWED_HOSTS when not explicitly provided
if not CSRF_TRUSTED_ORIGINS:
    derived_origins = []
    for host in ALLOWED_HOSTS:
        host = host.strip()
        if not host or host == '*':
            continue
        for scheme in ('http', 'https'):
            derived_origins.append(f"{scheme}://{host}")
            # also include common external port 8003 (our nginx mapping) if not already specified
            if ':' not in host:
                derived_origins.append(f"{scheme}://{host}:8003")
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(derived_origins))

# Jazzmin admin UI configuration (simple defaults; can be customized later)
JAZZMIN_SETTINGS = {
    "site_title": "Alpha Admin",
    "site_header": "Alpha 后台",
    "site_brand": "Alpha",
    "welcome_sign": "欢迎来到 Alpha 管理后台",
    "copyright": "Alpha",
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "dark_mode_theme": None,
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'drf_spectacular',
    'captcha',
    'mdeditor',
    'django_extensions',
    'debug_toolbar',
    
    # Local apps
    'apps.users',
    'apps.articles',
    'apps.categories',
    'apps.links',
    'apps.api',
    'apps.english',
    'apps.jobs',
    'apps.todos',
    'apps.ai',
    'apps.search',
    'feature_flags',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 缓存中间件
    'apps.api.cache_middleware.CacheHeadersMiddleware',
    'apps.api.cache_middleware.APICacheMiddleware',
    # 地道表达安全中间件
    'apps.english.middleware.EnglishSecurityMiddleware',
    'apps.english.middleware.ContentSecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'alpha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'alpha.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# SQLite 配置（开发环境备用）
DATABASES_SQLITE = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL 配置 - 支持Docker环境变量
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'alpha_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'meimei520'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+08:00'",
        },
    }
}

# SQLite 配置（开发环境备用）
# DATABASES = DATABASES_SQLITE

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# Disable timezone-aware datetimes in dev to avoid MySQL tz table dependency errors in admin
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 前端URL配置（用于密码重置邮件链接）
FRONTEND_URL = "http://localhost:3000"

# 邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 开发环境使用控制台输出
# 生产环境使用SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # 或其他SMTP服务器
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

DEFAULT_FROM_EMAIL = 'Alpha团队 <noreply@alpha.com>'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    # 基础限流设置，防止接口被滥用
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',   # 未登录用户
        'user': '240/minute',  # 登录用户
        # 地道表达模块专用限流
        'english_expressions': '120/minute',  # 表达式查询
        'english_learning': '60/minute',      # 学习功能
        'english_management': '30/minute',    # 管理功能
        'english_crawler': '10/minute',       # 爬虫功能
        'english_anon': '30/minute',          # 匿名用户访问英语模块
        'english_api': '100/minute',          # API密钥访问
    },
    'EXCEPTION_HANDLER': 'apps.api.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '2227208441@qq.com'
EMAIL_HOST_PASSWORD = 'rzzydlmqsxeuebij'  # QQ邮箱授权码
DEFAULT_FROM_EMAIL = '2227208441@qq.com'

# Email verification settings
EMAIL_VERIFICATION_TIMEOUT = 3600  # 1小时过期

# Captcha Configuration
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 1
CAPTCHA_IMAGE_SIZE = (160, 50)
CAPTCHA_FONT_SIZE = 28

# Debug Toolbar Configuration
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# Debug Toolbar Settings
def _show_toolbar(request):
    import os
    # 仅在开发且非pytest测试时展示
    return DEBUG and not os.environ.get('PYTEST_CURRENT_TEST')

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': _show_toolbar,
}

# Only enable debug toolbar in development
if DEBUG:
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]

# Cache Configuration
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/2')

# 开发环境：优先使用本地内存缓存，避免Redis依赖问题
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5分钟默认过期
    },
    # Redis缓存（生产环境使用）
    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'alpha_cache',
        'TIMEOUT': 300,  # 5分钟默认过期
    }
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# MDEditor Configuration
X_FRAME_OPTIONS = 'SAMEORIGIN'

# --- appended by setup: register english app ---
try:
    from .settings import *  # noqa
except Exception:
    pass

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/1')

# 外部API配置
# 牛津词典API
OXFORD_API_ID = os.environ.get('OXFORD_API_ID', '')
OXFORD_API_KEY = os.environ.get('OXFORD_API_KEY', '')

# 有道翻译API
YOUDAO_APP_KEY = os.environ.get('YOUDAO_APP_KEY', '')
YOUDAO_APP_SECRET = os.environ.get('YOUDAO_APP_SECRET', '')

# Google Cloud API
GOOGLE_CLOUD_API_KEY = os.environ.get('GOOGLE_CLOUD_API_KEY', '')

# Azure Speech Service
AZURE_SPEECH_API_KEY = os.environ.get('AZURE_SPEECH_API_KEY', '')
AZURE_SPEECH_REGION = os.environ.get('AZURE_SPEECH_REGION', 'eastus')

# 科大讯飞API
XFYUN_APP_ID = os.environ.get('XFYUN_APP_ID', '')
XFYUN_API_KEY = os.environ.get('XFYUN_API_KEY', '')
XFYUN_API_SECRET = os.environ.get('XFYUN_API_SECRET', '')
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'
CELERY_TIMEZONE = TIME_ZONE

# Fallback update when direct import above not applicable
try:
    if 'apps.english' not in INSTALLED_APPS:
        INSTALLED_APPS.append('apps.english')
except Exception:
    # If settings are static above, ignore
    pass

# 安全设置
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 强制HTTPS（生产环境）
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session安全
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# 地道表达安全配置
ENGLISH_SECURITY = {
    'API_KEY_EXPIRY_DAYS': 30,
    'MAX_API_KEYS_PER_USER': 3,
    'LOGIN_ATTEMPT_LIMIT': 5,
    'LOGIN_ATTEMPT_WINDOW_MINUTES': 15,
    'API_REQUEST_LIMIT_PER_HOUR': 1000,
    'CONTENT_MAX_LENGTH': 2000,
    'EXPRESSION_MAX_LENGTH': 500,
    'ENABLE_CONTENT_VALIDATION': True,
    'ENABLE_AUDIT_LOGGING': True,
}

# DRF Spectacular (OpenAPI 3.0) Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': '地道表达学习平台 API',
    'DESCRIPTION': '提供地道英语表达学习、数据采集和管理功能的RESTful API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
        'supportedSubmitMethods': ['get', 'post', 'put', 'delete', 'patch'],
        'oauth2RedirectUrl': '/api/v1/auth/oauth2-redirect/',
        'docExpansion': 'list',  # 默认展开操作列表
        'defaultModelRendering': 'schema',  # 默认显示模式
        'showExtensions': True,
        'showCommonExtensions': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'hideHostname': False,
        'hideLoading': False,
        'hideSchemaPattern': True,
        'scrollYOffset': 0,
        'suppressWarnings': True,
        'theme': {
            'colors': {
                'primary': {
                    'main': '#667eea'
                }
            },
            'typography': {
                'fontSize': '14px',
                'lineHeight': '1.5em',
                'code': {
                    'fontSize': '13px',
                    'fontFamily': 'Courier, monospace'
                }
            }
        },
        'menu': {
            'groupItems': True
        }
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'SORT_OPERATION_PARAMETERS': True,
    'ENUM_NAME_OVERRIDES': {
        'ValidationErrorEnum': 'apps.api.enums.ValidationErrorEnum',
    },
    'TAGS': [
        {'name': 'Authentication', 'description': '用户认证相关接口'},
        {'name': 'Expressions', 'description': '地道表达管理接口'},
        {'name': 'Learning', 'description': '学习功能接口'},
        {'name': 'Statistics', 'description': '学习数据统计接口'},
        {'name': 'AI Assistant', 'description': 'AI助教功能接口'},
        {'name': 'Management', 'description': '系统管理接口'},
        {'name': 'Security', 'description': '安全管理接口'},
        {'name': 'Cache', 'description': '缓存管理接口'},
        {'name': 'Monitoring', 'description': '系统监控接口'},
    ],
    # 'PREPROCESSING_HOOKS': [
    #     'apps.api.schema_hooks.preprocess_exclude_paths'
    # ],
    'POSTPROCESSING_HOOKS': [
        'apps.api.schema_hooks.postprocess_schema_enhancements'
    ],
    # API版本化支持
    'SCHEMA_COERCE_METHOD_NAMES': {
        'retrieve': 'get',
        'destroy': 'delete',
    },
    # 自定义字段映射
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT认证令牌，格式：Bearer <token>'
            }
        }
    },
    # 缓存设置
    'ENABLE_DJANGO_DEPLOY_CHECK': False,
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

# AI服务配置
AI_SERVICES = {
    'openai-gpt4': {
        'provider': 'openai',
        'model': 'gpt-4',
        'max_tokens': 4000,
        'temperature': 0.7,
        'timeout': 30,
        'weight': 3,
        'enabled': True
    },
    'openai-gpt35': {
        'provider': 'openai',
        'model': 'gpt-3.5-turbo',
        'max_tokens': 4000,
        'temperature': 0.7,
        'timeout': 30,
        'weight': 2,
        'enabled': True
    },
    'claude-sonnet': {
        'provider': 'anthropic',
        'model': 'claude-3-sonnet-20240229',
        'max_tokens': 4000,
        'temperature': 0.7,
        'timeout': 30,
        'weight': 3,
        'enabled': True
    },
    'claude-haiku': {
        'provider': 'anthropic',
        'model': 'claude-3-haiku-20240307',
        'max_tokens': 4000,
        'temperature': 0.7,
        'timeout': 30,
        'weight': 1,
        'enabled': True
    },
    'google-gemini': {
        'provider': 'google',
        'model': 'gemini-pro',
        'max_tokens': 4000,
        'temperature': 0.7,
        'timeout': 30,
        'weight': 2,
        'enabled': True
    }
}

# AI服务降级配置
AI_DEGRADATION_THRESHOLDS = {
    'degraded_cpu_threshold': 80.0,
    'degraded_memory_threshold': 85.0,
    'degraded_response_time': 5.0,
    'degraded_error_rate': 0.1,
    'degraded_queue_size': 100,
    'minimal_cpu_threshold': 95.0,
    'minimal_memory_threshold': 95.0,
    'minimal_response_time': 10.0,
    'minimal_error_rate': 0.3,
    'minimal_queue_size': 500,
    'disabled_cpu_threshold': 98.0,
    'disabled_memory_threshold': 98.0,
    'disabled_error_rate': 0.8,
    'disabled_queue_size': 1000,
}

# AI负载均衡配置
AI_LOAD_BALANCER = {
    'strategy': 'weighted_round_robin',  # 默认策略
    'health_check_interval': 60,  # 健康检查间隔（秒）
    'max_retries': 3,
    'retry_delay': 1.0,
    'connection_timeout': 30.0,
}
