# Generated by Django 4.2.7 on 2025-08-30 08:31

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_cost_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(db_index=True, max_length=50)),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField()),
                ('auto_accuracy_score', models.FloatField(blank=True, null=True)),
                ('auto_relevance_score', models.FloatField(blank=True, null=True)),
                ('auto_helpfulness_score', models.FloatField(blank=True, null=True)),
                ('auto_clarity_score', models.FloatField(blank=True, null=True)),
                ('auto_completeness_score', models.FloatField(blank=True, null=True)),
                ('auto_overall_score', models.FloatField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('user_thumbs_up', models.BooleanField(blank=True, null=True)),
                ('ai_model', models.CharField(max_length=100)),
                ('ai_provider', models.CharField(max_length=50)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_response_quality',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_response_user_id_7342da_idx'), models.Index(fields=['function_type', '-created_at'], name='ai_response_functio_7608c8_idx'), models.Index(fields=['ai_provider', '-created_at'], name='ai_response_ai_prov_001ee9_idx'), models.Index(fields=['-created_at'], name='ai_response_created_da02a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_saved', models.DateTimeField(blank=True, null=True)),
                ('messages_data', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('message_count', models.IntegerField(default=0)),
                ('estimated_tokens', models.IntegerField(default=0)),
                ('compression_count', models.IntegerField(default=0)),
                ('last_compression', models.DateTimeField(blank=True, null=True)),
                ('quality_scores', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('avg_quality_score', models.FloatField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('rating_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_activity', '-created_at'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='ai_conversa_user_id_673136_idx'), models.Index(fields=['user', '-created_at'], name='ai_conversa_user_id_7542e0_idx'), models.Index(fields=['-last_activity'], name='ai_conversa_last_ac_37f48d_idx'), models.Index(fields=['is_active', 'is_archived'], name='ai_conversa_is_acti_620f51_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(db_index=True, max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_usage_re_user_id_9bc335_idx'), models.Index(fields=['function_type', '-created_at'], name='ai_usage_re_functio_16b793_idx'), models.Index(fields=['provider', '-created_at'], name='ai_usage_re_provide_091254_idx'), models.Index(fields=['-created_at'], name='ai_usage_re_created_fc7cb1_idx')],
            },
        ),
    ]
