# Generated by Django 4.2.7 on 2025-08-31 16:27

from decimal import Decimal
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='模型ID', max_length=100)),
                ('display_name', models.CharField(help_text='显示名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模型描述')),
                ('max_tokens', models.IntegerField(help_text='最大Token数')),
                ('supports_streaming', models.BooleanField(default=True, help_text='是否支持流式响应')),
                ('supports_functions', models.BooleanField(default=False, help_text='是否支持函数调用')),
                ('supports_vision', models.BooleanField(default=False, help_text='是否支持视觉输入')),
                ('cost_per_1k_input_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='每1K输入Token成本(USD)', max_digits=10, null=True)),
                ('cost_per_1k_output_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='每1K输出Token成本(USD)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False, help_text='是否推荐使用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ['-is_recommended', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='提供商名称', max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('azure', 'Azure OpenAI'), ('local', 'Local (Ollama)'), ('chenmoai', 'ChenmoAI'), ('openrouter', 'OpenRouter'), ('siliconflow', 'SiliconFlow'), ('custom', 'Custom Provider')], help_text='提供商类型', max_length=20)),
                ('display_name', models.CharField(help_text='显示名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='提供商描述')),
                ('base_url', models.URLField(help_text='API基础URL')),
                ('api_version', models.CharField(blank=True, help_text='API版本', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('is_healthy', models.BooleanField(default=False, help_text='健康状态')),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_check_interval', models.IntegerField(default=300, help_text='健康检查间隔(秒)')),
                ('avg_response_time', models.FloatField(blank=True, help_text='平均响应时间(秒)', null=True)),
                ('success_rate', models.FloatField(blank=True, help_text='成功率(%)', null=True)),
                ('config_schema', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='配置模式')),
                ('default_config', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='默认配置')),
                ('rate_limit_per_minute', models.IntegerField(blank=True, help_text='每分钟请求限制', null=True)),
                ('rate_limit_per_day', models.IntegerField(blank=True, help_text='每日请求限制', null=True)),
                ('max_tokens_per_request', models.IntegerField(blank=True, help_text='单次请求最大Token', null=True)),
                ('cost_per_1k_input_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='每1K输入Token成本(USD)', max_digits=10, null=True)),
                ('cost_per_1k_output_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='每1K输出Token成本(USD)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='密钥名称', max_length=100)),
                ('key_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('encrypted_key', models.TextField(help_text='加密后的API密钥')),
                ('key_prefix', models.CharField(blank=True, help_text='密钥前缀(用于显示)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认密钥')),
                ('usage_limit_daily', models.IntegerField(blank=True, help_text='每日使用限制', null=True)),
                ('usage_limit_monthly', models.IntegerField(blank=True, help_text='每月使用限制', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='密钥过期时间', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ai.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_api_keys',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailoverRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='优先级(数字越小优先级越高)')),
                ('trigger_errors', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='触发的错误类型列表')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('fallback_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aimodel')),
                ('fallback_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_failover_rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('conversation_id', models.CharField(blank=True, help_text='对话ID', max_length=100)),
                ('input_tokens', models.IntegerField(help_text='输入Token数')),
                ('output_tokens', models.IntegerField(help_text='输出Token数')),
                ('total_tokens', models.IntegerField(help_text='总Token数')),
                ('input_cost', models.DecimalField(decimal_places=6, help_text='输入成本(USD)', max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, help_text='输出成本(USD)', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, help_text='总成本(USD)', max_digits=10)),
                ('response_time', models.FloatField(help_text='响应时间(秒)')),
                ('is_streaming', models.BooleanField(default=False, help_text='是否为流式响应')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '错误'), ('timeout', '超时'), ('rate_limit', '限流')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='ai.apikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='ai.aimodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='ai.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_token_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(help_text='配置名称', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='温度参数(0.0-2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(blank=True, help_text='最大生成Token数', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('top_p', models.FloatField(default=1.0, help_text='Top-p参数(0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frequency_penalty', models.FloatField(default=0.0, help_text='频率惩罚(-2.0-2.0)', validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)])),
                ('presence_penalty', models.FloatField(default=0.0, help_text='存在惩罚(-2.0-2.0)', validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)])),
                ('system_prompt', models.TextField(blank=True, help_text='系统提示')),
                ('custom_config', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='自定义配置')),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认配置')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='ai.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_configs',
                'ordering': ['-is_default', '-last_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailoverStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='策略名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='策略描述')),
                ('max_retries', models.IntegerField(default=3, help_text='最大重试次数')),
                ('retry_delay', models.IntegerField(default=1, help_text='重试延迟(秒)')),
                ('timeout_threshold', models.FloatField(default=30.0, help_text='超时阈值(秒)')),
                ('error_rate_threshold', models.FloatField(default=0.5, help_text='错误率阈值(0.0-1.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认策略')),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('fallback_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('fallback_providers', models.ManyToManyField(help_text='备用提供商', related_name='fallback_strategies', through='ai.FailoverRule', to='ai.aiprovider')),
                ('primary_model', models.ForeignKey(help_text='主要模型', on_delete=django.db.models.deletion.CASCADE, related_name='primary_strategies', to='ai.aimodel')),
                ('primary_provider', models.ForeignKey(help_text='主要提供商', on_delete=django.db.models.deletion.CASCADE, related_name='primary_strategies', to='ai.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_failover_strategies',
                'ordering': ['-is_default', '-last_used', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='failoverrule',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ai.failoverstrategy'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider'),
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('daily', '每日配额'), ('weekly', '每周配额'), ('monthly', '每月配额'), ('total', '总配额')], default='monthly', max_length=20)),
                ('token_limit', models.IntegerField(help_text='Token限制')),
                ('token_used', models.IntegerField(default=0, help_text='已使用Token')),
                ('cost_limit', models.DecimalField(blank=True, decimal_places=2, help_text='成本限制(USD)', max_digits=10, null=True)),
                ('cost_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='已使用成本(USD)', max_digits=10)),
                ('request_limit', models.IntegerField(blank=True, help_text='请求次数限制', null=True)),
                ('request_used', models.IntegerField(default=0, help_text='已使用请求次数')),
                ('is_active', models.BooleanField(default=True)),
                ('is_exceeded', models.BooleanField(default=False, help_text='是否超出配额')),
                ('period_start', models.DateTimeField(help_text='周期开始时间')),
                ('period_end', models.DateTimeField(help_text='周期结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='ai.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_quotas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider', 'quota_type'], name='ai_usage_qu_user_id_91ff24_idx'), models.Index(fields=['is_active', 'is_exceeded'], name='ai_usage_qu_is_acti_466a30_idx'), models.Index(fields=['period_end'], name='ai_usage_qu_period__04f1fa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagequota',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'quota_type', 'period_start'), name='unique_quota_per_user_provider_period'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['user', '-created_at'], name='ai_token_us_user_id_bb384c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['provider', '-created_at'], name='ai_token_us_provide_d11a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['model', '-created_at'], name='ai_token_us_model_i_92b0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['status', '-created_at'], name='ai_token_us_status_c9dfba_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['created_at'], name='ai_token_us_created_a83fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='modelconfig',
            index=models.Index(fields=['user', 'model', 'is_active'], name='ai_model_co_user_id_3a0740_idx'),
        ),
        migrations.AddIndex(
            model_name='modelconfig',
            index=models.Index(fields=['is_active', 'is_default'], name='ai_model_co_is_acti_185fa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'model', 'is_default'), name='unique_default_config_per_user_model'),
        ),
        migrations.AddIndex(
            model_name='failoverstrategy',
            index=models.Index(fields=['user', 'is_active'], name='ai_failover_user_id_cbbde6_idx'),
        ),
        migrations.AddIndex(
            model_name='failoverstrategy',
            index=models.Index(fields=['is_active', 'is_default'], name='ai_failover_is_acti_815f13_idx'),
        ),
        migrations.AddConstraint(
            model_name='failoverstrategy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_strategy_per_user'),
        ),
        migrations.AddIndex(
            model_name='failoverrule',
            index=models.Index(fields=['strategy', 'priority', 'is_active'], name='ai_failover_strateg_0cec68_idx'),
        ),
        migrations.AddConstraint(
            model_name='failoverrule',
            constraint=models.UniqueConstraint(fields=('strategy', 'priority'), name='unique_priority_per_strategy'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['provider', 'user', 'is_active'], name='ai_api_keys_provide_8208a8_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active', 'is_default'], name='ai_api_keys_is_acti_c97e22_idx'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider', 'user', 'is_default'), name='unique_default_key_per_provider_user'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['provider_type', 'is_active'], name='ai_provider_provide_b12c31_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['is_active', 'is_healthy'], name='ai_provider_is_acti_1ed18e_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider', 'is_active'], name='ai_models_provide_31dc69_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active', 'is_recommended'], name='ai_models_is_acti_21d097_idx'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_model_per_provider'),
        ),
    ]
