# Generated by Django 4.2.7 on 2025-08-31 16:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_config_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='encrypted_key',
            field=django_cryptography.fields.encrypt(models.CharField(help_text='加密后的API密钥', max_length=500)),
        ),
    ]
