# Generated by Django 4.2.7 on 2025-08-31 20:48

from decimal import Decimal
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_update_apikey_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(help_text='告警类型', max_length=50)),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', help_text='告警级别', max_length=20)),
                ('status', models.CharField(choices=[('active', '活跃'), ('resolved', '已解决'), ('acknowledged', '已确认'), ('suppressed', '已抑制')], default='active', help_text='告警状态', max_length=20)),
                ('title', models.CharField(help_text='告警标题', max_length=200)),
                ('message', models.TextField(help_text='告警详情')),
                ('service_name', models.CharField(blank=True, help_text='相关服务', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='解决时间', null=True)),
                ('rule_name', models.CharField(blank=True, help_text='触发的规则名称', max_length=100)),
                ('threshold_value', models.FloatField(blank=True, help_text='阈值', null=True)),
                ('actual_value', models.FloatField(blank=True, help_text='实际值', null=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='告警相关的额外数据')),
                ('provider', models.ForeignKey(blank=True, help_text='关联的AI提供商', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_system_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ai_system_a_status_831e8e_idx'), models.Index(fields=['level', '-created_at'], name='ai_system_a_level_82aaeb_idx'), models.Index(fields=['service_name', '-created_at'], name='ai_system_a_service_154fea_idx'), models.Index(fields=['provider', '-created_at'], name='ai_system_a_provide_42f80b_idx'), models.Index(fields=['-created_at'], name='ai_system_a_created_deab5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='服务名称', max_length=100)),
                ('status', models.CharField(choices=[('healthy', '健康'), ('degraded', '降级'), ('unhealthy', '不健康'), ('unknown', '未知')], default='unknown', help_text='健康状态', max_length=20)),
                ('is_healthy', models.BooleanField(default=True, help_text='是否健康')),
                ('response_time', models.FloatField(default=0.0, help_text='响应时间(秒)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='连续失败次数')),
                ('check_timestamp', models.DateTimeField(auto_now_add=True, help_text='检查时间')),
                ('check_type', models.CharField(choices=[('health_check', '健康检查'), ('api_call', 'API调用'), ('scheduled', '定时检查')], default='health_check', help_text='检查类型', max_length=50)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='额外的监控数据')),
                ('provider', models.ForeignKey(blank=True, help_text='关联的AI提供商', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_service_health_records',
                'ordering': ['-check_timestamp'],
                'indexes': [models.Index(fields=['service_name', '-check_timestamp'], name='ai_service__service_e2fde7_idx'), models.Index(fields=['provider', '-check_timestamp'], name='ai_service__provide_d3ff8a_idx'), models.Index(fields=['status', '-check_timestamp'], name='ai_service__status_02e898_idx'), models.Index(fields=['-check_timestamp'], name='ai_service__check_t_00a046_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='服务名称', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('period_start', models.DateTimeField(help_text='统计周期开始时间')),
                ('period_end', models.DateTimeField(help_text='统计周期结束时间')),
                ('total_requests', models.IntegerField(default=0, help_text='总请求数')),
                ('successful_requests', models.IntegerField(default=0, help_text='成功请求数')),
                ('failed_requests', models.IntegerField(default=0, help_text='失败请求数')),
                ('avg_response_time', models.FloatField(default=0.0, help_text='平均响应时间(秒)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_response_time', models.FloatField(default=0.0, help_text='最小响应时间(秒)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_response_time', models.FloatField(default=0.0, help_text='最大响应时间(秒)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('p95_response_time', models.FloatField(default=0.0, help_text='95分位响应时间(秒)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_input_tokens', models.BigIntegerField(default=0, help_text='总输入Token数')),
                ('total_output_tokens', models.BigIntegerField(default=0, help_text='总输出Token数')),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='总成本(USD)', max_digits=10)),
                ('qps', models.FloatField(default=0.0, help_text='每秒请求数', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('error_rate', models.FloatField(default=0.0, help_text='错误率(%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('success_rate', models.FloatField(default=100.0, help_text='成功率(%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='额外的性能数据')),
                ('provider', models.ForeignKey(blank=True, help_text='关联的AI提供商', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_performance_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service_name', '-timestamp'], name='ai_performa_service_16cece_idx'), models.Index(fields=['provider', '-timestamp'], name='ai_performa_provide_23eeda_idx'), models.Index(fields=['period_start', 'period_end'], name='ai_performa_period__89d037_idx'), models.Index(fields=['-timestamp'], name='ai_performa_timesta_253ae1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='performancemetric',
            constraint=models.UniqueConstraint(fields=('service_name', 'period_start', 'period_end'), name='unique_metric_per_service_period'),
        ),
    ]
