# Generated by Django 4.2.7 on 2025-08-31 23:14

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0004_add_monitoring_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('content', models.TextField(help_text='模板内容')),
                ('category', models.CharField(choices=[('general', '通用'), ('coding', '代码助手'), ('writing', '写作助手'), ('analysis', '分析助手'), ('translation', '翻译助手'), ('creative', '创意助手'), ('custom', '自定义')], default='general', help_text='模板分类', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='是否为公共模板')),
                ('is_system', models.BooleanField(default=False, help_text='是否为系统内置模板')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_prompt_templates',
                'ordering': ['-is_system', '-usage_count', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='modelconfig',
            new_name='ai_model_co_user_id_9ae397_idx',
            old_name='ai_model_co_user_id_3a0740_idx',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='custom_config',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='advanced_params',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='高级参数 (seed, stop_words, logit_bias, reserved_tokens等)'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to='ai.aiprovider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='system_prompt_template',
            field=models.TextField(blank=True, help_text='系统提示内容'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='model',
            field=models.CharField(help_text='模型ID', max_length=100),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='系统提示模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_configs', to='ai.prompttemplate'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['category', 'is_active'], name='ai_prompt_t_categor_58bb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['is_public', 'is_active'], name='ai_prompt_t_is_publ_546ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='ai_prompt_t_created_85221b_idx'),
        ),
    ]
