# Generated by Django 4.2.7 on 2025-09-01 00:09

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0005_add_prompt_template_and_update_model_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('auto_switch', '自动切换'), ('manual_switch', '手动切换'), ('recovery', '恢复'), ('health_check', '健康检查')], max_length=20, verbose_name='操作类型')),
                ('from_provider', models.CharField(blank=True, max_length=50, verbose_name='源提供商')),
                ('to_provider', models.CharField(max_length=50, verbose_name='目标提供商')),
                ('reason', models.TextField(verbose_name='切换原因')),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='额外的上下文信息', verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ai.failoverstrategy', verbose_name='故障转移策略')),
            ],
            options={
                'db_table': 'ai_fallback_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', 'action_type'], name='ai_fallback_strateg_1b2df7_idx'), models.Index(fields=['created_at'], name='ai_fallback_created_610b9c_idx')],
            },
        ),
    ]
