# Generated by Django 4.2.7 on 2025-09-01 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_add_fallback_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField(default=0, help_text='成功次数')),
                ('failure_count', models.IntegerField(default=0, help_text='失败次数')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='连续失败次数')),
                ('consecutive_successes', models.IntegerField(default=0, help_text='连续成功次数')),
                ('last_success_at', models.DateTimeField(blank=True, help_text='最后成功时间', null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, help_text='最后失败时间', null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='最后心跳时间', null=True)),
                ('avg_response_time', models.FloatField(blank=True, help_text='平均响应时间(秒)', null=True)),
                ('min_response_time', models.FloatField(blank=True, help_text='最小响应时间(秒)', null=True)),
                ('max_response_time', models.FloatField(blank=True, help_text='最大响应时间(秒)', null=True)),
                ('is_healthy', models.BooleanField(default=True, help_text='是否健康')),
                ('is_available', models.BooleanField(default=True, help_text='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_provider_health_statuses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='active_provider',
            field=models.ForeignKey(blank=True, help_text='当前活跃的提供商', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_strategies', to='ai.aiprovider'),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='cooldown',
            field=models.IntegerField(default=300, help_text='冷却时间（秒）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='fail_threshold',
            field=models.IntegerField(default=3, help_text='失败阈值（连续失败次数）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='jitter_window',
            field=models.IntegerField(default=60, help_text='抖动窗口（秒）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='last_switch_at',
            field=models.DateTimeField(blank=True, help_text='最后切换时间', null=True),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='recovery_threshold',
            field=models.IntegerField(default=5, help_text='恢复阈值（连续成功次数）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='failoverstrategy',
            name='strategy_mode',
            field=models.CharField(choices=[('priority', '优先级模式'), ('round_robin', '轮询模式')], default='priority', help_text='策略模式', max_length=20),
        ),
        migrations.AddIndex(
            model_name='failoverstrategy',
            index=models.Index(fields=['active_provider'], name='ai_failover_active__31a1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='failoverstrategy',
            index=models.Index(fields=['last_switch_at'], name='ai_failover_last_sw_fe56f7_idx'),
        ),
        migrations.AddField(
            model_name='providerhealthstatus',
            name='provider',
            field=models.ForeignKey(help_text='提供商', on_delete=django.db.models.deletion.CASCADE, related_name='health_statuses', to='ai.aiprovider'),
        ),
        migrations.AddField(
            model_name='providerhealthstatus',
            name='strategy',
            field=models.ForeignKey(help_text='关联的故障转移策略', on_delete=django.db.models.deletion.CASCADE, related_name='health_statuses', to='ai.failoverstrategy'),
        ),
        migrations.AddIndex(
            model_name='providerhealthstatus',
            index=models.Index(fields=['strategy', 'provider'], name='ai_provider_strateg_f4b5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhealthstatus',
            index=models.Index(fields=['is_healthy', 'is_available'], name='ai_provider_is_heal_9096b8_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhealthstatus',
            index=models.Index(fields=['last_heartbeat_at'], name='ai_provider_last_he_5cbe74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerhealthstatus',
            unique_together={('strategy', 'provider')},
        ),
    ]
