# Generated by Django 4.2.7 on 2025-09-01 21:37

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0007_providerhealthstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='版本名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='版本描述')),
                ('config_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='配置数据')),
                ('version_hash', models.CharField(help_text='版本哈希', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_versions', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, help_text='父版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='ai.configversion')),
            ],
            options={
                'db_table': 'ai_config_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'is_active'], name='ai_config_v_created_ef1464_idx'), models.Index(fields=['version_hash'], name='ai_config_v_version_93167b_idx'), models.Index(fields=['parent_version'], name='ai_config_v_parent__debb3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('config_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='配置数据')),
                ('tags', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='标签列表')),
                ('is_public', models.BooleanField(default=False, help_text='是否为公共模板')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_config_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'is_active'], name='ai_config_t_created_f1c74e_idx'), models.Index(fields=['is_public', 'is_active'], name='ai_config_t_is_publ_51a00e_idx')],
            },
        ),
    ]
