# Generated by Django 4.2.7 on 2025-09-01 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0008_configversion_configtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('category', models.CharField(choices=[('general', '通用'), ('security', '安全'), ('performance', '性能'), ('integration', '集成'), ('notification', '通知')], default='general', max_length=50, verbose_name='配置分类')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '自动')], default='auto', max_length=20, verbose_name='主题')),
                ('language', models.CharField(choices=[('zh-CN', '中文'), ('en-US', 'English')], default='zh-CN', max_length=10, verbose_name='语言')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('notification_frequency', models.CharField(choices=[('immediate', '立即'), ('daily', '每日'), ('weekly', '每周')], default='immediate', max_length=20, verbose_name='通知频率')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='双因素认证')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='会话超时(分钟)')),
                ('login_notifications', models.BooleanField(default=True, verbose_name='登录通知')),
                ('auto_save', models.BooleanField(default=True, verbose_name='自动保存')),
                ('debug_mode', models.BooleanField(default=False, verbose_name='调试模式')),
                ('analytics_enabled', models.BooleanField(default=True, verbose_name='启用分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='登录地点')),
                ('device_type', models.CharField(choices=[('desktop', '桌面'), ('mobile', '移动'), ('tablet', '平板')], max_length=20, verbose_name='设备类型')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('success', models.BooleanField(default=True, verbose_name='登录成功')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='会话键')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('desktop', '桌面'), ('mobile', '移动'), ('tablet', '平板')], max_length=20, verbose_name='设备类型')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '设备会话',
                'verbose_name_plural': '设备会话',
                'ordering': ['-last_activity'],
            },
        ),
    ]
