# Generated by Django 4.2.7 on 2025-08-25 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='特性名称')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='特性键值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('disabled', '禁用'), ('enabled', '启用'), ('rollout', '灰度发布'), ('deprecated', '已废弃')], default='disabled', max_length=20, verbose_name='状态')),
                ('target_type', models.CharField(choices=[('all', '所有用户'), ('percentage', '百分比用户'), ('user_list', '指定用户列表'), ('user_attribute', '用户属性'), ('environment', '环境')], default='all', max_length=20, verbose_name='目标类型')),
                ('rollout_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='灰度百分比')),
                ('target_users', models.JSONField(blank=True, default=list, verbose_name='目标用户列表')),
                ('user_attributes', models.JSONField(blank=True, default=dict, verbose_name='用户属性条件')),
                ('environments', models.JSONField(blank=True, default=list, verbose_name='环境列表')),
                ('value', models.JSONField(default=bool, verbose_name='特性值')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '特性开关',
                'verbose_name_plural': '特性开关',
                'db_table': 'feature_flags',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='会话ID')),
                ('is_enabled', models.BooleanField(verbose_name='是否启用')),
                ('value_returned', models.JSONField(verbose_name='返回值')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('environment', models.CharField(blank=True, max_length=50, verbose_name='环境')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('feature_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='feature_flags.featureflag', verbose_name='特性开关')),
                ('user', models.ForeignKey(blank=True, help_text='访问的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '特性开关使用记录',
                'verbose_name_plural': '特性开关使用记录',
                'db_table': 'feature_flag_usage',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['feature_flag', '-accessed_at'], name='feature_fla_feature_d1be15_idx'), models.Index(fields=['user', '-accessed_at'], name='feature_fla_user_id_2d1098_idx'), models.Index(fields=['is_enabled'], name='feature_fla_is_enab_37b8ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('environment', models.CharField(blank=True, max_length=50, verbose_name='环境')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('feature_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='feature_flags.featureflag', verbose_name='特性开关')),
            ],
            options={
                'verbose_name': '特性开关历史',
                'verbose_name_plural': '特性开关历史',
                'db_table': 'feature_flag_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['feature_flag', '-changed_at'], name='feature_fla_feature_2a410c_idx'), models.Index(fields=['action'], name='feature_fla_action_0cc09e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['key'], name='feature_fla_key_b4f409_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['status'], name='feature_fla_status_1818bc_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['target_type'], name='feature_fla_target__a1ad1f_idx'),
        ),
    ]
