# Generated by Django 4.2.7 on 2025-08-31 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('resource', models.CharField(help_text='如：user, article, ai_config', max_length=50, verbose_name='资源类型')),
                ('action', models.CharField(help_text='如：create, read, update, delete, manage', max_length=50, verbose_name='操作类型')),
                ('level', models.IntegerField(default=1, help_text='数值越大权限越高', verbose_name='权限级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'rbac_permission',
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('level', models.IntegerField(default=1, help_text='数值越大权限越高', verbose_name='角色级别')),
                ('is_system', models.BooleanField(default=False, help_text='系统角色不可删除', verbose_name='系统角色')),
                ('is_default', models.BooleanField(default=False, help_text='新用户的默认角色', verbose_name='默认角色')),
                ('max_users', models.IntegerField(blank=True, help_text='限制该角色的用户数量', null=True, verbose_name='最大用户数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.role', verbose_name='父角色')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.permission', verbose_name='权限列表')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'rbac_role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(blank=True, choices=[('', '无限制'), ('department', '部门'), ('project', '项目'), ('custom', '自定义')], max_length=20, verbose_name='权限范围类型')),
                ('scope_value', models.CharField(blank=True, max_length=100, verbose_name='权限范围值')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='分配者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'rbac_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('granted', models.BooleanField(default=True, verbose_name='是否授予权限')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权者')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源权限',
                'verbose_name_plural': '资源权限',
                'db_table': 'rbac_resource_permission',
                'unique_together': {('user', 'content_type', 'object_id', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='冗余存储，防止用户删除后丢失记录', max_length=150, verbose_name='用户名')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(blank=True, max_length=200, verbose_name='资源名称')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='变更前的值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='变更后的值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('request_url', models.URLField(blank=True, verbose_name='请求URL')),
                ('success', models.BooleanField(default=True, verbose_name='操作是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='操作耗时（秒）')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'rbac_audit_log',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rbac_audit__user_id_72163e_idx'), models.Index(fields=['action', 'timestamp'], name='rbac_audit__action_ae56ba_idx'), models.Index(fields=['resource_type', 'timestamp'], name='rbac_audit__resourc_c6285c_idx')],
            },
        ),
    ]
