# Generated by Django 4.2.7 on 2025-08-12 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("english", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="audio_url",
            field=models.URLField(blank=True, verbose_name="音频URL"),
        ),
        migrations.AddField(
            model_name="expression",
            name="usage_examples",
            field=models.TextField(blank=True, verbose_name="使用示例"),
        ),
        migrations.AddField(
            model_name="news",
            name="comprehension_questions",
            field=models.JSONField(blank=True, default=list, verbose_name="理解题目"),
        ),
        migrations.AddField(
            model_name="news",
            name="key_vocabulary",
            field=models.TextField(blank=True, verbose_name="关键词汇"),
        ),
        migrations.AddField(
            model_name="news",
            name="reading_time_minutes",
            field=models.IntegerField(default=0, verbose_name="阅读时长(分钟)"),
        ),
        migrations.AddField(
            model_name="userwordprogress",
            name="ease_factor",
            field=models.DecimalField(
                decimal_places=2, default=2.5, max_digits=4, verbose_name="容易度因子"
            ),
        ),
        migrations.AddField(
            model_name="userwordprogress",
            name="interval_days",
            field=models.IntegerField(default=1, verbose_name="复习间隔(天)"),
        ),
        migrations.AddField(
            model_name="userwordprogress",
            name="repetition_count",
            field=models.IntegerField(default=0, verbose_name="重复次数"),
        ),
        migrations.AddField(
            model_name="word",
            name="antonyms",
            field=models.TextField(blank=True, verbose_name="反义词"),
        ),
        migrations.AddField(
            model_name="word",
            name="audio_url",
            field=models.URLField(blank=True, verbose_name="音频URL"),
        ),
        migrations.AddField(
            model_name="word",
            name="etymology",
            field=models.TextField(blank=True, verbose_name="词源"),
        ),
        migrations.AddField(
            model_name="word",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="图片URL"),
        ),
        migrations.AddField(
            model_name="word",
            name="synonyms",
            field=models.TextField(blank=True, verbose_name="同义词"),
        ),
        migrations.CreateModel(
            name="PronunciationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("word_id", models.IntegerField(verbose_name="单词ID")),
                ("audio_file", models.CharField(max_length=500, verbose_name="音频文件路径")),
                (
                    "pronunciation_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="发音得分",
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="准确度得分",
                    ),
                ),
                (
                    "fluency_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="流利度得分",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="反馈建议")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "发音记录",
                "verbose_name_plural": "发音记录",
                "db_table": "english_pronunciation_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "practice_type",
                    models.CharField(
                        choices=[
                            ("word_spelling", "单词拼写"),
                            ("word_meaning", "单词释义"),
                            ("expression_usage", "表达运用"),
                            ("reading_comprehension", "阅读理解"),
                            ("pronunciation", "发音练习"),
                        ],
                        max_length=50,
                        verbose_name="练习类型",
                    ),
                ),
                ("content_id", models.IntegerField(verbose_name="内容ID")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("word", "单词"), ("expression", "表达"), ("news", "新闻")],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("question", models.TextField(verbose_name="题目")),
                ("user_answer", models.TextField(verbose_name="用户答案")),
                ("correct_answer", models.TextField(verbose_name="正确答案")),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="得分"
                    ),
                ),
                ("time_spent", models.IntegerField(help_text="秒", verbose_name="用时")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习记录",
                "verbose_name_plural": "练习记录",
                "db_table": "english_practice_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="计划名称")),
                ("description", models.TextField(blank=True, verbose_name="计划描述")),
                (
                    "daily_word_target",
                    models.IntegerField(default=10, verbose_name="每日单词目标"),
                ),
                (
                    "daily_expression_target",
                    models.IntegerField(default=5, verbose_name="每日表达目标"),
                ),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[("daily", "每日"), ("weekly", "每周"), ("custom", "自定义")],
                        default="daily",
                        max_length=20,
                        verbose_name="复习频率",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
                "db_table": "english_learning_plans",
            },
        ),
        migrations.CreateModel(
            name="LearningStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                ("words_learned", models.IntegerField(default=0, verbose_name="学习单词数")),
                (
                    "words_reviewed",
                    models.IntegerField(default=0, verbose_name="复习单词数"),
                ),
                (
                    "expressions_learned",
                    models.IntegerField(default=0, verbose_name="学习表达数"),
                ),
                ("news_read", models.IntegerField(default=0, verbose_name="阅读新闻数")),
                ("practice_count", models.IntegerField(default=0, verbose_name="练习次数")),
                (
                    "study_time_minutes",
                    models.IntegerField(default=0, verbose_name="学习时长(分钟)"),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="正确率"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习统计",
                "verbose_name_plural": "学习统计",
                "db_table": "english_learning_stats",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
