# Generated by Django 4.2.7 on 2025-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0002_expression_audio_url_expression_usage_examples_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_alt",
            field=models.CharField(blank=True, max_length=200, verbose_name="图片描述"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="图片URL"),
        ),
    ]
