# Generated by Django 4.2.7 on 2025-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0003_news_image_alt_news_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
    ]
