# Generated by Django 4.2.7 on 2025-08-16 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0004_news_is_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="is_visible",
        ),
    ]
