# Generated by Django 4.2.7 on 2025-08-16 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("english", "0005_remove_is_visible_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTypingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_words_practiced",
                    models.IntegerField(default=0, verbose_name="总练习单词数"),
                ),
                (
                    "total_correct_words",
                    models.IntegerField(default=0, verbose_name="总正确单词数"),
                ),
                ("average_wpm", models.FloatField(default=0.0, verbose_name="平均WPM")),
                (
                    "total_practice_time",
                    models.IntegerField(default=0, verbose_name="总练习时长(分钟)"),
                ),
                (
                    "last_practice_date",
                    models.DateField(blank=True, null=True, verbose_name="最后练习日期"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户打字统计",
                "verbose_name_plural": "用户打字统计",
                "db_table": "english_user_typing_stats",
            },
        ),
        migrations.CreateModel(
            name="TypingWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(max_length=100, unique=True, verbose_name="单词"),
                ),
                ("translation", models.CharField(max_length=200, verbose_name="翻译")),
                (
                    "phonetic",
                    models.CharField(blank=True, max_length=100, verbose_name="音标"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "初级"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="词库类别")),
                ("frequency", models.IntegerField(default=0, verbose_name="词频")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "打字练习单词",
                "verbose_name_plural": "打字练习单词",
                "db_table": "english_typing_word",
                "indexes": [
                    models.Index(
                        fields=["category", "difficulty"],
                        name="english_typ_categor_3f5b8c_idx",
                    ),
                    models.Index(fields=["word"], name="english_typ_word_b37dfb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TypingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                (
                    "typing_speed",
                    models.FloatField(default=0.0, verbose_name="打字速度(WPM)"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0.0, verbose_name="响应时间(秒)"),
                ),
                (
                    "session_date",
                    models.DateField(auto_now_add=True, verbose_name="练习日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="english.typingword",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "打字练习记录",
                "verbose_name_plural": "打字练习记录",
                "db_table": "english_typing_session",
                "indexes": [
                    models.Index(
                        fields=["user", "session_date"],
                        name="english_typ_user_id_b835e3_idx",
                    ),
                    models.Index(
                        fields=["word", "is_correct"],
                        name="english_typ_word_id_415c13_idx",
                    ),
                ],
            },
        ),
    ]
