# Generated by Django 4.2.7 on 2025-08-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0006_usertypingstats_typingword_typingsession"),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='词库名称')),
                ('description', models.TextField(blank=True, verbose_name='词库描述')),
                ('category', models.CharField(max_length=50, verbose_name='词库分类')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='语言')),
                ('total_words', models.IntegerField(default=0, verbose_name='总单词数')),
                ('chapter_count', models.IntegerField(default=1, verbose_name='章节数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('source_file', models.CharField(blank=True, max_length=200, verbose_name='源文件')),
            ],
            options={
                'verbose_name': '词库',
                'verbose_name_plural': '词库',
                'db_table': 'english_dictionary',
            },
        ),
        migrations.CreateModel(
            name='TypingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='单词')),
                ('translation', models.CharField(max_length=200, verbose_name='翻译')),
                ('phonetic', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('chapter', models.IntegerField(default=1, verbose_name='章节')),
                ('frequency', models.IntegerField(default=0, verbose_name='词频')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='english.dictionary', verbose_name='所属词库')),
            ],
            options={
                'verbose_name': '打字练习单词',
                'verbose_name_plural': '打字练习单词',
                'db_table': 'english_typing_word',
            },
        ),
        migrations.CreateModel(
            name='TypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('typing_speed', models.FloatField(default=0.0, verbose_name='打字速度(WPM)')),
                ('response_time', models.FloatField(default=0.0, verbose_name='响应时间(秒)')),
                ('session_date', models.DateField(auto_now_add=True, verbose_name='练习日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.typingword', verbose_name='单词')),
            ],
            options={
                'verbose_name': '打字练习记录',
                'verbose_name_plural': '打字练习记录',
                'db_table': 'english_typing_session',
            },
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['category'], name='english_dic_categor_a3367f_idx'),
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['is_active'], name='english_dic_is_acti_c57335_idx'),
        ),
        migrations.AddIndex(
            model_name='typingword',
            index=models.Index(fields=['dictionary', 'chapter'], name='english_typ_diction_7dc76d_idx'),
        ),
        migrations.AddIndex(
            model_name='typingword',
            index=models.Index(fields=['word'], name='english_typ_word_7dc76d_idx'),
        ),
        migrations.AddIndex(
            model_name='typingword',
            index=models.Index(fields=['difficulty'], name='english_typ_difficu_a3b70d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingword',
            unique_together={('word', 'dictionary')},
        ),
    ]
