# Generated by Django 4.2.7 on 2025-08-17 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("english", "0006_usertypingstats_typingword_typingsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPracticeStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                ("exercise_count", models.IntegerField(default=0, verbose_name="练习次数")),
                ("word_count", models.IntegerField(default=0, verbose_name="练习单词数")),
                ("total_time", models.FloatField(default=0, verbose_name="总用时(毫秒)")),
                ("wrong_count", models.IntegerField(default=0, verbose_name="总错误次数")),
                ("wrong_keys", models.JSONField(default=list, verbose_name="错误按键列表")),
                ("avg_wpm", models.FloatField(default=0, verbose_name="平均WPM")),
                ("accuracy_rate", models.FloatField(default=0, verbose_name="正确率")),
            ],
            options={
                "verbose_name": "每日练习统计",
                "verbose_name_plural": "每日练习统计",
                "db_table": "english_daily_practice_stats",
            },
        ),
        migrations.CreateModel(
            name="KeyErrorStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=10, verbose_name="按键")),
                ("error_count", models.IntegerField(default=0, verbose_name="错误次数")),
                (
                    "last_error_date",
                    models.DateField(auto_now=True, verbose_name="最后错误日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "按键错误统计",
                "verbose_name_plural": "按键错误统计",
                "db_table": "english_key_error_stats",
            },
        ),
        migrations.CreateModel(
            name="TypingPracticeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="单词")),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                ("typing_speed", models.FloatField(verbose_name="打字速度(WPM)")),
                ("response_time", models.FloatField(verbose_name="响应时间(秒)")),
                ("total_time", models.FloatField(verbose_name="总用时(毫秒)")),
                ("wrong_count", models.IntegerField(default=0, verbose_name="错误次数")),
                ("mistakes", models.JSONField(default=dict, verbose_name="按键错误详情")),
                ("timing", models.JSONField(default=list, verbose_name="每个字符的输入时间")),
                (
                    "session_date",
                    models.DateField(auto_now_add=True, verbose_name="练习日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "打字练习详细记录",
                "verbose_name_plural": "打字练习详细记录",
                "db_table": "english_typing_practice_records",
            },
        ),

        migrations.AddIndex(
            model_name="typingsession",
            index=models.Index(
                fields=["user", "session_date"], name="english_typ_user_id_b835e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="typingsession",
            index=models.Index(
                fields=["word", "is_correct"], name="english_typ_word_id_415c13_idx"
            ),
        ),
        migrations.AddField(
            model_name="typingpracticerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="keyerrorstats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="dailypracticestats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="typingpracticerecord",
            index=models.Index(
                fields=["user", "session_date"], name="english_typ_user_id_69be03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="typingpracticerecord",
            index=models.Index(
                fields=["user", "created_at"], name="english_typ_user_id_777cec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keyerrorstats",
            index=models.Index(
                fields=["user", "error_count"], name="english_key_user_id_a6dbc1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="keyerrorstats",
            unique_together={("user", "key")},
        ),
        migrations.AddIndex(
            model_name="dailypracticestats",
            index=models.Index(
                fields=["user", "date"], name="english_dai_user_id_446b7a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailypracticestats",
            unique_together={("user", "date")},
        ),
    ]
