# Generated by Django 5.2.5 on 2025-08-21 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0009_dailypracticestats_keyerrorstats_and_more"),
    ]

    operations = []
