# Generated by Django 5.2.5 on 2025-08-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0010_mark_current_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypingPracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dictionary", models.CharField(max_length=100, verbose_name="词库")),
                ("chapter", models.IntegerField(default=1, verbose_name="章节")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("total_words", models.IntegerField(default=0, verbose_name="总单词数")),
                ("correct_words", models.IntegerField(default=0, verbose_name="正确单词数")),
                ("total_time", models.FloatField(default=0.0, verbose_name="总用时(秒)")),
                ("average_wpm", models.FloatField(default=0.0, verbose_name="平均WPM")),
                ("accuracy_rate", models.FloatField(default=0.0, verbose_name="正确率")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "session_date",
                    models.DateField(auto_now_add=True, verbose_name="练习日期"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "打字练习会话",
                "verbose_name_plural": "打字练习会话",
                "db_table": "english_typing_practice_sessions",
            },
        ),
        migrations.AddField(
            model_name="typingpracticerecord",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="english.typingpracticesession",
                verbose_name="练习会话",
            ),
        ),
        migrations.AddIndex(
            model_name="typingpracticerecord",
            index=models.Index(
                fields=["session"], name="english_typ_session_7f896b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="typingpracticesession",
            index=models.Index(
                fields=["user", "session_date"], name="english_typ_user_id_7ee5c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="typingpracticesession",
            index=models.Index(
                fields=["user", "is_completed"], name="english_typ_user_id_f590d2_idx"
            ),
        ),
    ]
