# Generated by Django 4.2.7 on 2025-08-24 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("english", "0011_typingpracticesession_typingpracticerecord_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrongWordRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("word", models.CharField(max_length=100, verbose_name="单词")),
                ("translation", models.CharField(max_length=200, verbose_name="翻译")),
                (
                    "dictionary_id",
                    models.CharField(max_length=100, verbose_name="词典ID"),
                ),
                ("error_count", models.IntegerField(default=1, verbose_name="错误次数")),
                (
                    "last_error_date",
                    models.DateTimeField(auto_now=True, verbose_name="最后错误时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题记录",
                "verbose_name_plural": "错题记录",
                "db_table": "english_wrong_word_records",
                "indexes": [
                    models.Index(
                        fields=["user", "dictionary_id"],
                        name="english_wro_user_id_9702a2_idx",
                    ),
                    models.Index(
                        fields=["user", "last_error_date"],
                        name="english_wro_user_id_821951_idx",
                    ),
                ],
                "unique_together": {("user", "word", "dictionary_id")},
            },
        ),
        migrations.CreateModel(
            name="DailyPracticeDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "total_duration_minutes",
                    models.IntegerField(default=0, verbose_name="总练习时长(分钟)"),
                ),
                ("session_count", models.IntegerField(default=0, verbose_name="练习会话数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日练习时长",
                "verbose_name_plural": "每日练习时长",
                "db_table": "english_daily_practice_duration",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="english_dai_user_id_a3555b_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="ChapterPracticeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "dictionary_id",
                    models.CharField(max_length=100, verbose_name="词典ID"),
                ),
                ("chapter_number", models.IntegerField(verbose_name="章节号")),
                ("practice_count", models.IntegerField(default=0, verbose_name="练习次数")),
                (
                    "last_practice_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后练习时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节练习记录",
                "verbose_name_plural": "章节练习记录",
                "db_table": "english_chapter_practice_records",
                "indexes": [
                    models.Index(
                        fields=["user", "dictionary_id"],
                        name="english_cha_user_id_4e737e_idx",
                    ),
                    models.Index(
                        fields=["user", "dictionary_id", "chapter_number"],
                        name="english_cha_user_id_c8a455_idx",
                    ),
                ],
                "unique_together": {("user", "dictionary_id", "chapter_number")},
            },
        ),
    ]
