# Generated by Django 4.2.7 on 2025-08-29 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0012_wrongwordrecord_dailypracticeduration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('config_name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('azure', 'Azure OpenAI'), ('local', '本地模型'), ('custom', '自定义')], default='openai', max_length=20, verbose_name='AI提供商')),
                ('model_name', models.CharField(help_text='如gpt-4, claude-3-sonnet等', max_length=100, verbose_name='模型名称')),
                ('api_endpoint', models.URLField(blank=True, help_text='自定义API端点URL', verbose_name='API端点')),
                ('max_tokens', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='最大令牌数')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, help_text='控制输出的随机性，0-2之间', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='温度参数')),
                ('system_prompt', models.TextField(default='你是一个专业的英语学习助教，专门帮助学生学习地道表达。', verbose_name='系统提示词模板')),
                ('extended_config', models.JSONField(blank=True, default=dict, help_text='存储特定模型的额外配置参数', verbose_name='扩展配置参数')),
                ('api_key_encrypted', models.TextField(blank=True, help_text='请勿直接存储明文密钥', verbose_name='加密的API密钥')),
                ('is_active', models.BooleanField(default=False, help_text='同时只能有一个配置处于激活状态', verbose_name='是否激活')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='配置版本')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': 'AI助教配置',
                'verbose_name_plural': 'AI助教配置',
                'db_table': 'english_ai_assistant_configs',
            },
        ),
        migrations.CreateModel(
            name='ExpressionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('scenario_name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('context_description', models.TextField(help_text='详细描述该场景的使用背景', verbose_name='上下文描述')),
                ('example_dialogue', models.TextField(blank=True, help_text='展示表达在实际对话中的使用', verbose_name='示例对话')),
                ('scenario_type', models.CharField(choices=[('business', '商务场合'), ('casual', '日常交流'), ('academic', '学术场合'), ('social', '社交场合'), ('travel', '旅行出行'), ('workplace', '职场环境'), ('entertainment', '娱乐休闲')], default='casual', max_length=20, verbose_name='场景类型')),
            ],
            options={
                'verbose_name': '表达场景',
                'verbose_name_plural': '表达场景',
                'db_table': 'english_expression_scenarios',
            },
        ),
        migrations.CreateModel(
            name='ExpressionScenarioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=2, default=5.0, help_text='表达在该场景中的相关性和适用性', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='相关性评分(0-10)')),
                ('usage_frequency', models.CharField(choices=[('rare', '很少'), ('occasional', '偶尔'), ('common', '常见'), ('frequent', '频繁')], default='common', max_length=10, verbose_name='在该场景中的使用频率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '表达-场景关联',
                'verbose_name_plural': '表达-场景关联',
                'db_table': 'english_expression_scenario_links',
            },
        ),
        migrations.CreateModel(
            name='ExpressionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('source_name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('source_url', models.URLField(blank=True, verbose_name='数据源URL')),
                ('source_type', models.CharField(choices=[('dictionary', '词典'), ('forum', '论坛'), ('news', '新闻媒体'), ('social_media', '社交媒体'), ('academic', '学术资料'), ('literature', '文学作品'), ('movie_tv', '影视作品'), ('manual', '人工录入')], default='manual', max_length=20, verbose_name='数据源类型')),
                ('reliability_score', models.DecimalField(decimal_places=2, default=5.0, help_text='数据源的可靠性和权威性评分', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='可靠性评分(0-10)')),
                ('description', models.TextField(blank=True, verbose_name='数据源描述')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '表达数据源',
                'verbose_name_plural': '表达数据源',
                'db_table': 'english_expression_sources',
            },
        ),
        migrations.CreateModel(
            name='IdiomaticExpression',
            fields=[
                ('expression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='english.expression')),
                ('expression_type', models.CharField(choices=[('idiom', '习语'), ('slang', '俚语'), ('collocation', '固定搭配'), ('phrase', '短语'), ('proverb', '谚语'), ('metaphor', '隐喻表达')], default='phrase', max_length=20, verbose_name='表达类型')),
                ('frequency_score', models.IntegerField(default=5, help_text='1=极少使用, 10=极常使用', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='使用频率评分(1-10)')),
                ('formality_level', models.CharField(choices=[('informal', '非正式'), ('neutral', '中性'), ('formal', '正式')], default='neutral', max_length=10, verbose_name='正式程度')),
                ('phonetic_transcription', models.CharField(blank=True, help_text='IPA音标记录', max_length=200, verbose_name='音标')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储变体形式、同义表达、相关表达等', verbose_name='扩展元数据')),
            ],
            options={
                'verbose_name': '地道表达',
                'verbose_name_plural': '地道表达',
                'db_table': 'english_idiomatic_expressions',
            },
            bases=('english.expression',),
        ),
        migrations.CreateModel(
            name='UserExpressionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('mastery_level', models.IntegerField(default=0, help_text='0=完全不会, 100=完全掌握', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='掌握程度(0-100)')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('next_review', models.DateTimeField(blank=True, null=True, verbose_name='下次复习时间')),
                ('learning_streak', models.IntegerField(default=0, verbose_name='连续学习天数')),
                ('easiness_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='容易度因子')),
                ('interval', models.IntegerField(default=1, verbose_name='复习间隔(天)')),
                ('learning_history', models.JSONField(blank=True, default=list, help_text='存储每次学习的详细记录', verbose_name='学习历史记录')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.idiomaticexpression', verbose_name='表达')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户表达进度',
                'verbose_name_plural': '用户表达进度',
                'db_table': 'english_user_expression_progress',
            },
        ),
        migrations.AddIndex(
            model_name='idiomaticexpression',
            index=models.Index(fields=['expression_type'], name='english_idi_express_fc0a34_idx'),
        ),
        migrations.AddIndex(
            model_name='idiomaticexpression',
            index=models.Index(fields=['frequency_score'], name='english_idi_frequen_9f5841_idx'),
        ),
        migrations.AddIndex(
            model_name='idiomaticexpression',
            index=models.Index(fields=['formality_level'], name='english_idi_formali_cb4aca_idx'),
        ),
        migrations.AddIndex(
            model_name='idiomaticexpression',
            index=models.Index(fields=['expression_type', 'frequency_score'], name='english_idi_express_99285d_idx'),
        ),
        migrations.AddField(
            model_name='expressionsource',
            name='expressions',
            field=models.ManyToManyField(blank=True, related_name='sources', to='english.idiomaticexpression', verbose_name='关联表达'),
        ),
        migrations.AddField(
            model_name='expressionscenariolink',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.idiomaticexpression', verbose_name='表达'),
        ),
        migrations.AddField(
            model_name='expressionscenariolink',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.expressionscenario', verbose_name='场景'),
        ),
        migrations.AddField(
            model_name='expressionscenario',
            name='expressions',
            field=models.ManyToManyField(related_name='scenarios', through='english.ExpressionScenarioLink', to='english.idiomaticexpression', verbose_name='关联表达'),
        ),
        migrations.AddIndex(
            model_name='aiassistantconfig',
            index=models.Index(fields=['ai_provider'], name='english_ai__ai_prov_733617_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantconfig',
            index=models.Index(fields=['is_active'], name='english_ai__is_acti_5826ab_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantconfig',
            index=models.Index(fields=['last_used'], name='english_ai__last_us_11ef49_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'next_review'], name='english_use_user_id_7a13b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'mastery_level'], name='english_use_user_id_03f93a_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'last_reviewed'], name='english_use_user_id_176411_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userexpressionprogress',
            unique_together={('user', 'expression')},
        ),
        migrations.AddIndex(
            model_name='expressionsource',
            index=models.Index(fields=['source_type'], name='english_exp_source__952696_idx'),
        ),
        migrations.AddIndex(
            model_name='expressionsource',
            index=models.Index(fields=['reliability_score'], name='english_exp_reliabi_91b5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expressionsource',
            index=models.Index(fields=['last_updated'], name='english_exp_last_up_3eb32c_idx'),
        ),
        migrations.AddIndex(
            model_name='expressionscenariolink',
            index=models.Index(fields=['expression', 'relevance_score'], name='english_exp_express_508e28_idx'),
        ),
        migrations.AddIndex(
            model_name='expressionscenariolink',
            index=models.Index(fields=['scenario', 'usage_frequency'], name='english_exp_scenari_89f7f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expressionscenariolink',
            unique_together={('expression', 'scenario')},
        ),
        migrations.AddIndex(
            model_name='expressionscenario',
            index=models.Index(fields=['scenario_type'], name='english_exp_scenari_cadaae_idx'),
        ),
        migrations.AddIndex(
            model_name='expressionscenario',
            index=models.Index(fields=['scenario_name'], name='english_exp_scenari_23043e_idx'),
        ),
    ]
