# Generated by Django 4.2.7 on 2025-08-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_aiassistantconfig_expressionscenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionscenariolink',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_links', to='english.idiomaticexpression', verbose_name='表达'),
        ),
    ]
