# Generated by Django 4.2.7 on 2025-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0014_alter_expressionscenariolink_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='usage_examples',
            field=models.JSONField(blank=True, default=list, verbose_name='使用示例'),
        ),
    ]
