# Generated by Django 4.2.7 on 2025-08-30 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_alter_expression_usage_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='learning_difficulty',
            field=models.CharField(default='beginner', max_length=20, verbose_name='学习难度'),
        ),
        migrations.AddField(
            model_name='expression',
            name='popularity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='受欢迎度'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='average_response_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='用户回答问题的平均用时', max_digits=6, verbose_name='平均响应时间(秒)'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='best_learning_time',
            field=models.CharField(blank=True, help_text='用户学习效果最好的时间段', max_length=20, verbose_name='最佳学习时间段'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='consecutive_correct',
            field=models.IntegerField(default=0, help_text='当前连续答对的次数', verbose_name='连续正确次数'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='difficulty_rating',
            field=models.IntegerField(default=3, help_text='用户主观感受的难度等级', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度评级(1-5)'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='engagement_score',
            field=models.IntegerField(default=0, help_text='基于学习行为计算的参与度指标', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='参与度评分(0-100)'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='learning_context',
            field=models.JSONField(blank=True, default=dict, help_text='记录学习环境、设备、时间段等上下文信息', verbose_name='学习上下文'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='learning_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='基于时间和正确率计算的学习效率指标', max_digits=5, verbose_name='学习效率'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='max_consecutive_correct',
            field=models.IntegerField(default=0, help_text='历史上连续答对的最高记录', verbose_name='最大连续正确次数'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='mistake_patterns',
            field=models.JSONField(blank=True, default=dict, help_text='记录用户常犯错误的类型和频次', verbose_name='错误模式'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='用户笔记'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='retention_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='基于遗忘曲线计算的记忆保持率', max_digits=5, verbose_name='记忆保持率'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='study_duration',
            field=models.IntegerField(default=0, help_text='用户在该表达上花费的总学习时间', verbose_name='累计学习时长(秒)'),
        ),
        migrations.AddField(
            model_name='userexpressionprogress',
            name='total_attempts',
            field=models.IntegerField(default=0, help_text='包括正确和错误的总尝试次数', verbose_name='总尝试次数'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'learning_efficiency'], name='english_use_user_id_0b275f_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'engagement_score'], name='english_use_user_id_b2a2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'difficulty_rating'], name='english_use_user_id_c3f331_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'retention_rate'], name='english_use_user_id_f75437_idx'),
        ),
        migrations.AddIndex(
            model_name='userexpressionprogress',
            index=models.Index(fields=['user', 'study_duration'], name='english_use_user_id_916b2a_idx'),
        ),
    ]
