# Generated by Django 4.2.7 on 2025-08-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_expression_learning_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='词库名称')),
                ('description', models.TextField(blank=True, verbose_name='词库描述')),
                ('category', models.CharField(max_length=50, verbose_name='词库分类')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='语言')),
                ('total_words', models.IntegerField(default=0, verbose_name='总单词数')),
                ('chapter_count', models.IntegerField(default=1, verbose_name='章节数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('source_file', models.CharField(blank=True, max_length=200, verbose_name='源文件')),
            ],
            options={
                'verbose_name': '词库',
                'verbose_name_plural': '词库',
                'db_table': 'english_dictionary',
            },
        ),
        migrations.RemoveIndex(
            model_name='typingword',
            name='english_typ_categor_3f5b8c_idx',
        ),
        migrations.AddField(
            model_name='typingword',
            name='chapter',
            field=models.IntegerField(default=1, verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='typingword',
            name='word',
            field=models.CharField(max_length=100, verbose_name='单词'),
        ),
        migrations.AddIndex(
            model_name='typingword',
            index=models.Index(fields=['dictionary', 'chapter'], name='english_typ_diction_7dc76d_idx'),
        ),
        migrations.AddIndex(
            model_name='typingword',
            index=models.Index(fields=['difficulty'], name='english_typ_difficu_a3b70a_idx'),
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['category'], name='english_dic_categor_a3367f_idx'),
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['is_active'], name='english_dic_is_acti_c57335_idx'),
        ),
        migrations.AddField(
            model_name='typingword',
            name='dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='english.dictionary', verbose_name='所属词库'),
        ),
        migrations.AlterUniqueTogether(
            name='typingword',
            unique_together={('word', 'dictionary')},
        ),
        migrations.RemoveField(
            model_name='typingword',
            name='category',
        ),
    ]
